### PR TITLE
Change opts validation

### LINKED ISSUE #2: Elixir version constraint invalid
In this line https://github.com/wingyplus/redoc_ui_plug/blob/main/lib/plug/redoc_ui.ex#L51, we use `Keyword.validate` which present on Elixir 1.13+ but the Elixir version constraint set to 1.12 that the library cannot use it. The possible way to fix this is:

* Set version constraint to v1.13.
* Change `Keyword.validate` with other.

### PR DESCRIPTION
**Pull request by dcdourado**
Closes #2

Looked for references on Plug repo on how to enforce some opt. It just uses Keyword.fetch!/2:
https://github.com/elixir-plug/plug/blob/main/lib/plug/session.ex#L54

### CODE REVIEW

**Comment by wingyplus** [comment]
we should lower the elixir version constraint to 1.12 in mix.exs.

**Comment by dcdourado** [comment]
Isn't it already? https://github.com/dcdourado/redoc_ui_plug/blob/fix-opts-setup/mix.exs#L8

**Comment by wingyplus** [comment]
> Isn't it already? https://github.com/dcdourado/redoc_ui_plug/blob/fix-opts-setup/mix.exs#L8

You’re right. Sorry, my bad. 🙇‍♂️

**Comment by wingyplus** [comment]
I’ll take a look at it tomorrow.

**Comment by dcdourado** [comment]
When you have the time to review this PR @wingyplus, I have another one based on changes here.

**Comment by wingyplus** [comment]
@dcdourado FYI: #4 and #5 release on 0.2.0, published on hex.pm. :)

**Pull request merged**
